"""Segmented interrupted-time-series analysis of the FLP grade series.

Reconstruction analysis requested by the INFEDU editorial decision
(2026-07-13): analyse the complete semester series with a segmented /
interrupted-time-series approach, treat 2020-I and 2020-II separately,
and separate observed temporal patterns from causal interpretation.

Design
------
Time axis: half-year index (consecutive calendar semesters differ by 1),
so gaps in the offering history (2016-I, 2017-II, 2021-I, 2023-II, ...)
are respected as missing time, not compressed.

Segments:
  baseline   2015-II .. 2019-II   (7 offerings)
  D2020I     2020-I  (emergency remote teaching, own dummy)
  D2020II    2020-II (flipped intervention semester, own dummy)
  sustained  2021-II .. 2026-I    (9 offerings, flipped era)

Primary model (OLS, HAC/Newey-West lag-1 sensitivity):
  y = b0 + b1*t + b2*POST + b3*(t - t_first_post)*POST
        + g1*D2020I + g2*D2020II
so b2 is the level change at the start of the sustained era relative to
the projected baseline, and b3 the trend change.

Sensitivities: enrollment-weighted WLS; binomial GLM on approved/enrolled
counts; segment descriptives with Welch t, variance ratio, Levene, and
Mann-Kendall trend tests per segment.

2019-II uses the thesis-official cohort (48 enrolled, 22 approved, 45.8%),
consistent with Table 1 of the manuscript.

Run:
  bash containers/run.sh paper-data python \
      papers/education-individual/data/its_analysis.py
"""

import os
import math

import numpy as np
import pandas as pd
from scipy import stats
import statsmodels.api as sm

CSV = os.path.join(os.path.dirname(__file__), "..", "data", "grade-series-2015-2026.csv")
OUT = os.path.join(os.path.dirname(__file__), "..", "results", "its-analysis.md")

df = pd.read_csv(CSV)

# 2019-II: thesis-official cohort (authoritative source, matches Table 1).
m = df["semester"] == "2019-II"
df.loc[m, ["enrolled", "approved", "failed", "withdrawn"]] = [48, 22, 16, 10]
df.loc[m, "pass_rate_enrolled"] = 45.8

df["approval"] = 100.0 * df["approved"] / df["enrolled"]


def t_index(sem):
    year, half = sem.split("-")
    return (int(year) - 2015) * 2 + (0 if half == "I" else 1)


df["t"] = df["semester"].map(t_index)
df = df.sort_values("t").reset_index(drop=True)

df["d2020i"] = (df["semester"] == "2020-I").astype(float)
df["d2020ii"] = (df["semester"] == "2020-II").astype(float)
df["post"] = (df["t"] >= t_index("2021-II")).astype(float)
t0 = t_index("2021-II")
df["post_t"] = np.where(df["post"] == 1, df["t"] - t0, 0.0)

base = df[df["t"] <= t_index("2019-II")]
sust = df[df["post"] == 1]

lines = []
add = lines.append
add("# Segmented ITS analysis of the FLP series (generated by its_analysis.py)")
add("")
add("2019-II uses the thesis-official cohort (48 enrolled, 22 approved).")
add("Time axis: half-year index; calendar gaps preserved.")
add("")


def mann_kendall(x):
    """Two-sided Mann-Kendall trend test; returns (S, z, p)."""
    x = np.asarray(x, dtype=float)
    n = len(x)
    s = sum(
        np.sign(x[j] - x[i]) for i in range(n - 1) for j in range(i + 1, n)
    )
    uniq, counts = np.unique(x, return_counts=True)
    var = (n * (n - 1) * (2 * n + 5)
           - sum(c * (c - 1) * (2 * c + 5) for c in counts)) / 18.0
    if var == 0:
        return s, 0.0, 1.0
    z = (s - np.sign(s)) / math.sqrt(var) if s != 0 else 0.0
    return s, z, 2 * (1 - stats.norm.cdf(abs(z)))


def describe_segments(y, label, unit):
    b, s_ = base[y], sust[y]
    add(f"## {label}: segment descriptives")
    add("")
    add(f"- baseline 2015-II..2019-II (n={len(b)}): mean {b.mean():.2f}, "
        f"SD {b.std(ddof=1):.2f}, range {b.min():.2f}-{b.max():.2f} {unit}")
    add(f"- 2020-I (ERT): {df.loc[df.d2020i == 1, y].iloc[0]:.2f} {unit}; "
        f"2020-II (intervention): {df.loc[df.d2020ii == 1, y].iloc[0]:.2f} {unit}")
    add(f"- sustained 2021-II..2026-I (n={len(s_)}): mean {s_.mean():.2f}, "
        f"SD {s_.std(ddof=1):.2f}, range {s_.min():.2f}-{s_.max():.2f} {unit}")
    tt = stats.ttest_ind(s_, b, equal_var=False)
    dmean = s_.mean() - b.mean()
    add(f"- Welch t (sustained - baseline): diff {dmean:+.2f} {unit}, "
        f"t={tt.statistic:.2f}, df={tt.df:.1f}, p={tt.pvalue:.4f}")
    # Hedges g on segment-level points
    sp = math.sqrt(((len(b) - 1) * b.var(ddof=1) + (len(s_) - 1) * s_.var(ddof=1))
                   / (len(b) + len(s_) - 2))
    g = (dmean / sp) * (1 - 3 / (4 * (len(b) + len(s_)) - 9))
    add(f"- Hedges g (semester-level points): {g:.2f}")
    fr = b.var(ddof=1) / s_.var(ddof=1)
    pf = 2 * min(stats.f.cdf(fr, len(b) - 1, len(s_) - 1),
                 1 - stats.f.cdf(fr, len(b) - 1, len(s_) - 1))
    lev = stats.levene(b, s_, center="median")
    add(f"- variance ratio baseline/sustained: {fr:.2f} "
        f"(F-test p={pf:.4f}; Brown-Forsythe p={lev.pvalue:.4f})")
    for name, seg in (("baseline", b), ("sustained", s_)):
        s_mk, z, p = mann_kendall(seg.values)
        add(f"- Mann-Kendall {name}: S={s_mk:+.0f}, z={z:.2f}, p={p:.4f}")
    add("")


def its_ols(y, label, unit):
    X = sm.add_constant(df[["t", "post", "post_t", "d2020i", "d2020ii"]])
    ols = sm.OLS(df[y], X).fit()
    hac = ols.get_robustcov_results(cov_type="HAC", maxlags=1)
    wls = sm.WLS(df[y], X, weights=df["enrolled"]).fit()
    dw = sm.stats.stattools.durbin_watson(ols.resid)
    add(f"## {label}: segmented ITS regression ({unit})")
    add("")
    add("| term | coef | OLS p | HAC p | WLS coef | WLS p |")
    add("|---|---|---|---|---|---|")
    names = ["const", "t", "post", "post_t", "d2020i", "d2020ii"]
    for i, nm in enumerate(names):
        add(f"| {nm} | {ols.params.iloc[i]:+.3f} | {ols.pvalues.iloc[i]:.4f} "
            f"| {hac.pvalues[i]:.4f} | {wls.params.iloc[i]:+.3f} "
            f"| {wls.pvalues.iloc[i]:.4f} |")
    ci = ols.conf_int()
    add("")
    add(f"- level change at 2021-II (post): {ols.params['post']:+.2f} "
        f"[{ci.loc['post', 0]:.2f}, {ci.loc['post', 1]:.2f}] {unit}")
    add(f"- baseline trend (t): {ols.params['t']:+.3f}/semester; "
        f"trend change (post_t): {ols.params['post_t']:+.3f}/semester")
    add(f"- R2 {ols.rsquared:.3f}, adj {ols.rsquared_adj:.3f}, "
        f"Durbin-Watson {dw:.2f}, n={len(df)}")
    add("")
    return ols


describe_segments("approval", "Approval rate", "pp")
its_ols("approval", "Approval rate", "percentage points")

# Binomial GLM on counts (naturally enrollment-weighted)
X = sm.add_constant(df[["t", "post", "post_t", "d2020i", "d2020ii"]])
glm = sm.GLM(
    np.column_stack([df["approved"], df["enrolled"] - df["approved"]]),
    X, family=sm.families.Binomial(),
).fit()
add("## Approval: binomial GLM sensitivity (log-odds)")
add("")
add("| term | coef | p |")
add("|---|---|---|")
for nm in ["const", "t", "post", "post_t", "d2020i", "d2020ii"]:
    add(f"| {nm} | {glm.params[nm]:+.3f} | {glm.pvalues[nm]:.4f} |")
add(f"\n- post odds ratio: {math.exp(glm.params['post']):.2f} "
    f"[{math.exp(glm.conf_int().loc['post', 0]):.2f}, "
    f"{math.exp(glm.conf_int().loc['post', 1]):.2f}]")
add("")

describe_segments("mean_final_grade", "Mean final grade", "grade pts")
its_ols("mean_final_grade", "Mean final grade", "grade points (0-5)")

# Sensitivity: drop the two pandemic semesters entirely
sub = df[(df.d2020i == 0) & (df.d2020ii == 0)]
Xs = sm.add_constant(sub[["t", "post", "post_t"]])
add("## Sensitivity: pandemic semesters excluded (2020-I, 2020-II dropped)")
add("")
for y, unit in (("approval", "pp"), ("mean_final_grade", "grade pts")):
    o = sm.OLS(sub[y], Xs).fit()
    add(f"- {y}: post level change {o.params['post']:+.2f} {unit} "
        f"(p={o.pvalues['post']:.4f}); trend change "
        f"{o.params['post_t']:+.3f}/sem (p={o.pvalues['post_t']:.4f})")
add("")

# 2020-I vs 2020-II explicit contrast (the editor's point)
r0 = df[df.semester == "2020-I"].iloc[0]
r1 = df[df.semester == "2020-II"].iloc[0]
z2 = sm.stats.proportions_ztest(
    [int(r0.approved), int(r1.approved)],
    [int(r0.enrolled), int(r1.enrolled)])
add("## 2020-I vs 2020-II explicit contrast")
add("")
add(f"- 2020-I approval {r0.approval:.1f}% ({int(r0.approved)}/{int(r0.enrolled)}), "
    f"mean {r0.mean_final_grade:.2f}; 2020-II approval {r1.approval:.1f}% "
    f"({int(r1.approved)}/{int(r1.enrolled)}), mean {r1.mean_final_grade:.2f}")
add(f"- two-proportion z = {z2[0]:.2f}, p = {z2[1]:.4f} "
    "(2020-I HIGHER than the intervention semester)")
add("")

# Evaluation series correlation check (values from Table 3 of the manuscript)
ev = pd.DataFrame({
    "semester": ["2018-I", "2018-II", "2019-I", "2019-II", "2020-I", "2020-II",
                 "2021-II", "2022-II", "2023-I", "2024-I", "2024-II", "2025-I",
                 "2025-II", "2026-I"],
    "eval_mean": [4.71, 4.65, 5.00, 4.97, 4.92, 5.00, 4.91, 4.87, 4.71, 4.74,
                  4.56, 4.28, 4.24, 4.82],
})
mrg = ev.merge(df[["semester", "approval"]], on="semester")
pr = stats.pearsonr(mrg.eval_mean, mrg.approval)
sr = stats.spearmanr(mrg.eval_mean, mrg.approval)
add("## Evaluation mean vs approval (14 shared semesters)")
add("")
add(f"- Pearson r = {pr.statistic:.2f}, p = {pr.pvalue:.4f}; "
    f"Spearman rho = {sr.statistic:.2f}, p = {sr.pvalue:.4f}")
add("")

# Segment descriptives under the unified segmentation
# (baseline / pandemic transition 2020-I+2020-II / sustained 2021-II+)
add("## Unified segmentation descriptives")
add("")
segs = {
    "baseline": df[df.t <= t_index("2019-II")],
    "transition": df[(df.d2020i == 1) | (df.d2020ii == 1)],
    "sustained": df[df.post == 1],
}
for name, seg in segs.items():
    w = 100.0 * seg.approved.sum() / seg.enrolled.sum()
    add(f"- {name}: enrolled-weighted approval {w:.1f}% "
        f"({int(seg.approved.sum())}/{int(seg.enrolled.sum())}); "
        f"unweighted mean grade {seg.mean_final_grade.mean():.2f}")
add("")
ev_seg = {
    "baseline (2018-I..2019-II)": ev[ev.semester.isin(
        ["2018-I", "2018-II", "2019-I", "2019-II"])],
    "transition (2020-I, 2020-II)": ev[ev.semester.isin(
        ["2020-I", "2020-II"])],
    "sustained (2021-II..2026-I)": ev[~ev.semester.isin(
        ["2018-I", "2018-II", "2019-I", "2019-II", "2020-I", "2020-II"])],
}
add("### Evaluation means by unified segment (95% CI over semester points)")
add("")
for name, seg in ev_seg.items():
    mvals = seg.eval_mean
    if len(mvals) > 2:
        ci = stats.t.interval(0.95, len(mvals) - 1, loc=mvals.mean(),
                              scale=mvals.std(ddof=1) / math.sqrt(len(mvals)))
        add(f"- {name}: mean {mvals.mean():.2f} [{ci[0]:.2f}, {ci[1]:.2f}] "
            f"(n={len(mvals)})")
    else:
        add(f"- {name}: values {', '.join(f'{v:.2f}' for v in mvals)} "
            "(too few points for a CI)")
add("")

# Robustness additions from the 2026-07-13 review round (referee2 / domain
# review): overdispersion-adjusted binomial, Fisher exact for 2020-I vs
# 2020-II, leave-one-out sensitivities, divergence without 2026-I, Pearson
# CI, Cohen's h under the thesis-official 2019-II proportions, and the
# roster-figure sensitivity for 2019-II.
add("## Robustness additions (review round 2026-07-13)")
add("")

# Quasi-binomial: scale the naive binomial covariance by Pearson chi2/df.
disp = (glm.resid_pearson**2).sum() / glm.df_resid
se_q = glm.bse * math.sqrt(disp)
add(f"- binomial dispersion (Pearson chi2/df): {disp:.2f} "
    f"(df={glm.df_resid:.0f}); quasi-binomial SEs = naive x {math.sqrt(disp):.2f}")
for nm in ["post", "post_t", "d2020i", "d2020ii"]:
    z = glm.params[nm] / se_q[nm]
    p = 2 * (1 - stats.norm.cdf(abs(z)))
    lo, hi = (glm.params[nm] - 1.96 * se_q[nm], glm.params[nm] + 1.96 * se_q[nm])
    add(f"- quasi-binomial {nm}: OR {math.exp(glm.params[nm]):.2f} "
        f"[{math.exp(lo):.2f}, {math.exp(hi):.2f}], z={z:.2f}, p={p:.3f}")
add("")

# Fisher exact for 2020-I vs 2020-II (normal approximation unreliable: the
# 2020-I failure cell is a single student).
odd, pf = stats.fisher_exact([[27, 1], [43, 12]])
add(f"- 2020-I vs 2020-II Fisher exact: p={pf:.4f} (z-test gave p=0.0306)")
add("")

# Leave-one-out: drop the 2019-II anchor from the whole fit.
loo = df[df.semester != "2019-II"]
Xl = sm.add_constant(loo[["t", "post", "post_t", "d2020i", "d2020ii"]])
for y, unit in (("mean_final_grade", "grade pts"), ("approval", "pp")):
    o = sm.OLS(loo[y], Xl).fit()
    add(f"- LOO drop 2019-II, {y}: baseline trend {o.params['t']:+.3f}/sem, "
        f"post level {o.params['post']:+.2f} {unit} (p={o.pvalues['post']:.4f})")
base_l = loo[loo.t <= t_index("2019-I")]
for y, unit in (("approval", "pp"), ("mean_final_grade", "grade pts")):
    tt = stats.ttest_ind(sust[y], base_l[y], equal_var=False)
    add(f"- LOO drop 2019-II, Welch segment contrast, {y}: "
        f"{sust[y].mean() - base_l[y].mean():+.2f} {unit} "
        f"(t={tt.statistic:.2f}, p={tt.pvalue:.4f})")
add("")

# Divergence with and without the provisional 2026-I endpoint; Pearson CI.
zr = math.atanh(pr.statistic)
sez = 1 / math.sqrt(len(mrg) - 3)
ci_r = (math.tanh(zr - 1.96 * sez), math.tanh(zr + 1.96 * sez))
add(f"- Pearson r={pr.statistic:.2f}, 95% CI [{ci_r[0]:.2f}, {ci_r[1]:.2f}] "
    f"(Fisher z, n={len(mrg)})")
m13 = mrg[mrg.semester != "2026-I"]
pr13 = stats.pearsonr(m13.eval_mean, m13.approval)
add(f"- excluding 2026-I: r={pr13.statistic:.2f}, p={pr13.pvalue:.4f} (n={len(m13)})")
add("")

# Cohen's h for the demoted 2019-II -> 2020-II contrast, thesis-official
# proportions (45.8% -> 78.2%).
h = 2 * (math.asin(math.sqrt(0.782)) - math.asin(math.sqrt(0.458)))
add(f"- Cohen's h (45.8% -> 78.2%, thesis-official proportions): {h:.2f}")
add("")

# Sensitivity: 2019-II under the local roster figure (38 enrolled, 17
# approved, 44.7%) instead of the thesis-official cohort. The thesis figure
# stays primary everywhere; this bounds the provenance difference.
ros = df.copy()
m = ros["semester"] == "2019-II"
ros.loc[m, ["enrolled", "approved", "failed", "withdrawn"]] = [38, 17, 18, 3]
ros["approval"] = 100.0 * ros["approved"] / ros["enrolled"]
Xr = sm.add_constant(ros[["t", "post", "post_t", "d2020i", "d2020ii"]])
for y, unit in (("approval", "pp"), ("mean_final_grade", "grade pts")):
    o = sm.OLS(ros[y], Xr).fit()
    add(f"- roster-2019-II sensitivity, {y}: post level {o.params['post']:+.2f} "
        f"{unit} (p={o.pvalues['post']:.4f})")
add("")

with open(OUT, "w") as fh:
    fh.write("\n".join(lines))
print("\n".join(lines))
print(f"\nwritten: {OUT}")
